### ISSUE TITLE
Users drop-down only shows the first 10 users

### ISSUE THREAD

**Issue by julia-and** [skttl/umbraco-impersonator#3]
The Impersonator user selection drop-down seems to only include the first 10 users. We are using Impersonator 2.0.0 in Umbraco 11. I did briefly look at the Angular controller/template that creates the impersonator UI, and it looks like it should be working. Are you able to reproduce this on your side?

**Comment by yawkale** [comment]
the fix is very easy src/Our.Umbraco.Impersonator/wwwroot/user.controller.js line 28 is Number.MAX_SAFE_INTEGER very big and ignored by .net, you can use 2147483647
