### ISSUE TITLE
You can select yourself in the drop down

### ISSUE THREAD

**Issue by Rockerby** [skttl/umbraco-impersonator#6]
Currently when going to impersonate a user, your current user appears in the drop-down list. If you try and impersonate yourself you get an error saying the selection is invalid, but I think this shouldn't be an option to select.

I'm logged in as the only user, Administrator, in the below screenshot:
![image](https://github.com/skttl/umbraco-impersonator/assets/5808078/a38ebe0a-303b-44e4-a2bc-cea165e66e3e)

**Comment by skttl** [comment]
You are right, we should filter out the current user from the select box.

Also, if the current user is the only one, we probably shouldn't even display the impersonation option.
